require('dotenv').config();
const express=require('express');
const {Pool}=require('pg');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const helmet=require('helmet');
const cors=require('cors');
const rateLimit=require('express-rate-limit');
const {z}=require('zod');
const multer=require('multer');
const {put}=require('@vercel/blob');
const {serveBlob,mapPrivateBlobUrls,blobProxyUrlFor}=require('./blob-proxy');

const app=express();
app.set('trust proxy',1);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(_,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif|avif|svg\+xml)$/i.test(file.mimetype))});
app.use(helmet());
app.use(cors({origin:process.env.WEB_ORIGIN||true,credentials:true}));
app.use(express.json({limit:'1mb'}));
app.use(rateLimit({windowMs:60000,max:120}));
// Rewrite private Vercel Blob URLs into same-origin /api/blob/... proxy URLs
// in every JSON response, and serve the blobs themselves. This keeps uploaded
// images displayable after a refresh in both the Vercel deployment and local dev.
app.use((req,res,next)=>{const originalJson=res.json.bind(res);res.json=body=>originalJson(mapPrivateBlobUrls(body));next();});
app.use((req,res,next)=>{const url=req.originalUrl||req.url||'';if(url.split('?')[0]==='/api/blob'||url.split('?')[0].startsWith('/api/blob/'))return serveBlob(req,res);next();});
const q=(sql,args)=>pool.query(sql,args);
const auth=(req,res,next)=>{try{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');if(!token)throw Error();req.admin=jwt.verify(token,process.env.SESSION_SECRET);next()}catch{res.status(401).json({error:'Authentication required'})}};
const slug=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||`product-${Date.now()}`;
const money=n=>Math.round(Number(n)*100)/100;
const final=p=>{const d=p.discount_type==='percent'?Number(p.price)*Number(p.discount_value||0)/100:p.discount_type==='fixed'?Number(p.discount_value||0):0;return Math.max(0,money(Number(p.price)-d));};
const productSchema=z.object({nameEn:z.string().min(2),nameAr:z.string().min(2),price:z.coerce.number().nonnegative(),discountType:z.enum(['none','percent','fixed']).default('none'),discountValue:z.coerce.number().nonnegative().default(0),stock:z.coerce.number().int().nonnegative().default(0),categoryId:z.string().uuid().nullable().optional(),descriptionEn:z.string().optional().default(''),descriptionAr:z.string().optional().default(''),tags:z.array(z.string()).default([]),specifications:z.array(z.string()).default([]),active:z.boolean().default(true),featured:z.boolean().default(false),bestseller:z.boolean().default(false),newArrival:z.boolean().default(false)});

app.get('/api/health',async(_,res)=>{try{await q('select 1');res.json({ok:true,database:true,blob:Boolean(process.env.BLOB_STORE_ID||process.env.BLOB_READ_WRITE_TOKEN)})}catch(e){res.status(503).json({ok:false,database:false,blob:Boolean(process.env.BLOB_STORE_ID||process.env.BLOB_READ_WRITE_TOKEN)})}});
app.get('/api/settings/logo',async(_,res)=>{try{const x=(await q("select value from site_settings where key='logo' limit 1")).rows[0];res.json({logo:x?.value||null})}catch(e){res.status(500).json({error:'Settings unavailable'})}});
app.put('/api/settings/logo',async(req,res)=>{try{if(typeof req.body.logo!=='string'||req.body.logo.length>4000000)return res.status(400).json({error:'Invalid logo'});await q("insert into site_settings(key,value) values('logo',$1) on conflict(key) do update set value=excluded.value,updated_at=now()",[req.body.logo]);res.json({logo:req.body.logo})}catch(e){res.status(500).json({error:'Logo could not be saved'})}});

async function blobUpload(path,file){if(!file)return null;if(!(process.env.BLOB_STORE_ID||process.env.BLOB_READ_WRITE_TOKEN))throw Error('Vercel Blob is not configured');return put(path,file.buffer,{access:'private',contentType:file.mimetype,addRandomSuffix:false});}
app.post('/api/admin/upload',auth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Image file is required'});const folder=String(req.body.folder||'products').replace(/[^a-zA-Z0-9_-]/g,'-');const safe=req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'-');const blob=await blobUpload(`safa/${folder}/${Date.now()}-${safe}`,req.file);res.status(201).json({url:blobProxyUrlFor(blob.pathname),pathname:blob.pathname,contentType:blob.contentType})}catch(e){res.status(500).json({error:e.message||'Image upload failed'})}});
app.post('/api/admin/products/:id/images',auth,upload.single('file'),async(req,res)=>{try{const exists=await q('select id from products where id=$1',[req.params.id]);if(!exists.rows[0])return res.status(404).json({error:'Product not found'});if(!req.file)return res.status(400).json({error:'Image file is required'});const safe=req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'-');const blob=await blobUpload(`safa/products/${req.params.id}/${Date.now()}-${safe}`,req.file);const position=Number(req.body.position||0);const row=(await q('insert into product_images(product_id,url,alt_en,alt_ar,position) values($1,$2,$3,$4,$5) returning *',[req.params.id,blobProxyUrlFor(blob.pathname),String(req.body.altEn||''),String(req.body.altAr||''),position])).rows[0];res.status(201).json(row)}catch(e){res.status(500).json({error:e.message||'Product image upload failed'})}});
app.post('/api/admin/logo/upload',auth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Image file is required'});const safe=req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'-');const blob=await blobUpload(`safa/branding/logo-${Date.now()}-${safe}`,req.file);await q("insert into site_settings(key,value) values('logo',$1) on conflict(key) do update set value=excluded.value,updated_at=now()",[blobProxyUrlFor(blob.pathname)]);res.status(201).json({logo:blobProxyUrlFor(blob.pathname)})}catch(e){res.status(500).json({error:e.message||'Logo upload failed'})}});

app.post('/api/admin/login',async(req,res)=>{try{const {email,password}=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const a=(await q('select * from admins where email=$1',[email])).rows[0];if(!a||!await bcrypt.compare(password,a.password_hash))return res.status(401).json({error:'Invalid credentials'});res.json({token:jwt.sign({id:a.id,email:a.email},process.env.SESSION_SECRET,{expiresIn:'8h'})})}catch(e){res.status(400).json({error:'Invalid request'})}});

app.get('/api/products',async(req,res)=>{try{let{q:term,category,featured}=req.query;let sql="select p.*,c.name_en category_en,c.name_ar category_ar,coalesce((select json_agg(pi order by pi.position,pi.id) from product_images pi where pi.product_id=p.id),'[]'::json) images from products p left join categories c on c.id=p.category_id where p.active=true";const args=[];if(category){args.push(category);sql+=` and p.category_id=$${args.length}`}if(featured){args.push(featured==='true');sql+=` and p.featured=$${args.length}`}if(term){args.push(term);sql+=` and (p.name_en ilike '%'||$${args.length}||'%' or p.name_ar ilike '%'||$${args.length}||'%' or p.description_en ilike '%'||$${args.length}||'%' or $${args.length}=any(p.tags))`}const rows=(await q(sql+' order by p.created_at desc',args)).rows;res.json(rows.map(x=>({...x,final_price:final(x)})))}catch(e){res.status(500).json({error:'Products unavailable'})}});
app.get('/api/products/:id/images',async(req,res)=>{try{res.json((await q('select * from product_images where product_id=$1 order by position,id',[req.params.id])).rows)}catch(e){res.status(500).json({error:'Images unavailable'})}});
app.get('/api/categories',async(_,res)=>{try{const rows=(await q(`select c.*,coalesce((select pi.url from products p join product_images pi on pi.product_id=p.id where p.category_id=c.id and p.active=true order by (select coalesce(sum(oi.quantity),0) from order_items oi where oi.product_id=p.id) desc,p.bestseller desc,p.created_at desc,pi.position,pi.id limit 1),c.image_url) category_image_url from categories c where c.active=true order by c.position,c.name_en`)).rows;res.json(rows)}catch(e){res.status(500).json({error:'Categories unavailable'})}});
app.get('/api/offers',async(_,res)=>{try{const rows=(await q(`select o.*,coalesce(json_agg(json_build_object('id',p.id,'name_en',p.name_en,'name_ar',p.name_ar,'price',p.price,'images',(select json_agg(pi order by pi.position,pi.id) from product_images pi where pi.product_id=p.id))) filter (where p.id is not null),'[]'::json) products from offers o left join offer_items oi on oi.offer_id=o.id left join products p on p.id=oi.product_id where o.active=true and (o.start_date is null or o.start_date<=now()) and (o.end_date is null or o.end_date>=now()) group by o.id order by o.start_date desc nulls last`)).rows;res.json(rows)}catch(e){res.status(500).json({error:'Offers unavailable'})}});

app.post('/api/orders',async(req,res)=>{try{const s=z.object({customerName:z.string().min(2),phone1:z.string().regex(/^\+?\d{10,15}$/),phone2:z.string().regex(/^\+?\d{10,15}$/),governorate:z.string().min(2),address:z.string().min(5),buildingNumber:z.string().optional().default(''),apartmentNumber:z.string().optional().default(''),items:z.array(z.object({productId:z.string().uuid(),quantity:z.number().int().positive(),selectedSpecification:z.string().max(200).optional().default('')})).min(1)}).parse(req.body);const norm=x=>x.replace(/\D/g,'');if(norm(s.phone1)===norm(s.phone2))return res.status(400).json({error:'Phone numbers must be different'});const c=await pool.connect();try{await c.query('begin');let subtotal=0,discount=0,items=[];for(const i of s.items){const r=await c.query('select * from products where id=$1 and active=true for update',[i.productId]);if(!r.rows[0]||r.rows[0].stock<i.quantity)throw Error('Out of stock');const p=r.rows[0],unit=final(p);subtotal+=Number(p.price)*i.quantity;discount+=(Number(p.price)-unit)*i.quantity;items.push({p,i,unit})}const number='SAF-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),total=money(subtotal-discount);const o=(await c.query('insert into orders(order_number,customer_name,phone1,phone2,governorate,address,building_number,apartment_number,subtotal,discount,savings,total) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10,$11) returning *',[number,s.customerName,s.phone1,s.phone2,s.governorate,s.address,s.buildingNumber,s.apartmentNumber,subtotal,discount,total])).rows[0];for(const x of items){await c.query('insert into order_items(order_id,product_id,product_name_snapshot,price_snapshot,quantity,discount_snapshot,total,selected_specification) values($1,$2,$3,$4,$5,$6,$7,$8)',[o.id,x.p.id,x.p.name_en,x.unit,x.i.quantity,(Number(x.p.price)-x.unit)*x.i.quantity,x.unit*x.i.quantity,x.i.selectedSpecification||'']);await c.query('update products set stock=stock-$1,updated_at=now() where id=$2',[x.i.quantity,x.p.id])}await c.query('commit');res.status(201).json(o)}catch(e){await c.query('rollback');res.status(400).json({error:e.message})}finally{c.release()}}catch(e){res.status(400).json({error:'Invalid checkout data'})}});

app.get('/api/admin/stats',auth,async(_,res)=>{try{res.json((await q("select (select count(*) from orders) orders,(select count(*) from products where active) products,(select count(*) from categories where active) categories,(select count(*) from offers where active and (start_date is null or start_date<=now()) and (end_date is null or end_date>=now())) offers,(select coalesce(sum(total),0) from orders where status<>'cancelled') revenue")).rows[0])}catch(e){res.status(500).json({error:'Stats unavailable'})}});
app.get('/api/admin/orders',auth,async(_,res)=>{try{const rows=(await q(`select o.*,coalesce((select json_agg(json_build_object('id',oi.id,'productId',oi.product_id,'name',oi.product_name_snapshot,'quantity',oi.quantity,'unitPrice',oi.price_snapshot,'discount',oi.discount_snapshot,'total',oi.total,'specification',oi.selected_specification,'image',coalesce((select pi.url from product_images pi where pi.product_id=oi.product_id order by pi.position,pi.id limit 1),''))) from order_items oi where oi.order_id=o.id),'[]'::json) items from orders o order by o.created_at desc`)).rows;res.json(rows)}catch(e){res.status(500).json({error:'Orders unavailable'})}});
app.patch('/api/admin/orders/:id',auth,async(req,res)=>{try{const s=z.object({status:z.enum(['new','confirmed','preparing','shipped','delivered','cancelled'])}).parse(req.body);const row=(await q('update orders set status=$1,updated_at=now() where id=$2 returning *',[s.status,req.params.id])).rows[0];if(!row)return res.status(404).json({error:'Order not found'});res.json(row)}catch(e){res.status(400).json({error:'Invalid order update'})}});
app.get('/api/admin/products',auth,async(_,res)=>{try{const rows=(await q("select p.*,c.name_en category_en,c.name_ar category_ar,coalesce((select json_agg(pi order by pi.position,pi.id) from product_images pi where pi.product_id=p.id),'[]'::json) images from products p left join categories c on c.id=p.category_id order by p.created_at desc")).rows;res.json(rows.map(x=>({...x,final_price:final(x)})))}catch(e){res.status(500).json({error:'Products unavailable'})}});
app.post('/api/admin/products',auth,async(req,res)=>{try{const x=productSchema.parse(req.body);const base=slug(x.nameEn);let productSlug=base;for(let i=1;(await q('select 1 from products where slug=$1',[productSlug])).rows[0];i++)productSlug=`${base}-${i}`;const r=await q('insert into products(name_en,name_ar,slug,description_en,description_ar,price,discount_type,discount_value,stock,category_id,tags,active,featured,bestseller,new_arrival,specifications) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) returning *',[x.nameEn,x.nameAr,productSlug,x.descriptionEn,x.descriptionAr,x.price,x.discountType,x.discountValue,x.stock,x.categoryId||null,x.tags,x.active,x.featured,x.bestseller,x.newArrival,x.specifications]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/admin/products/:id',auth,async(req,res)=>{try{const x=productSchema.partial().parse(req.body);const fields=[];const args=[];const map={nameEn:'name_en',nameAr:'name_ar',descriptionEn:'description_en',descriptionAr:'description_ar',price:'price',specifications:'specifications',discountType:'discount_type',discountValue:'discount_value',stock:'stock',categoryId:'category_id',tags:'tags',active:'active',featured:'featured',bestseller:'bestseller',newArrival:'new_arrival'};for(const[k,v]of Object.entries(x)){if(!map[k])continue;fields.push(`${map[k]}=$${args.length+1}`);args.push(v)}if(!fields.length)return res.status(400).json({error:'No changes'});args.push(req.params.id);const row=(await q(`update products set ${fields.join(',')},updated_at=now() where id=$${args.length} returning *`,args)).rows[0];if(!row)return res.status(404).json({error:'Product not found'});res.json(row)}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/admin/products/:id',auth,async(req,res)=>{try{await q('update products set active=false,updated_at=now() where id=$1',[req.params.id]);res.status(204).end()}catch(e){res.status(400).json({error:'Product could not be deleted'})}});
app.get('/api/admin/categories',auth,async(_,res)=>res.json((await q('select * from categories order by position,name_en')).rows));
app.get('/api/admin/offers',auth,async(_,res)=>res.json((await q(`select o.*,coalesce(json_agg(json_build_object('id',p.id,'name_en',p.name_en)) filter(where p.id is not null),'[]'::json) products from offers o left join offer_items oi on oi.offer_id=o.id left join products p on p.id=oi.product_id group by o.id order by o.start_date desc nulls last`)).rows));
app.post('/api/admin/offers',auth,async(req,res)=>{try{const x=z.object({titleEn:z.string().min(2),titleAr:z.string().min(2),type:z.enum(['percentage','fixed','bundle','buy_x_get_y']),value:z.coerce.number().nonnegative().default(0),bundlePrice:z.coerce.number().nonnegative().nullable().optional(),buyX:z.coerce.number().int().positive().nullable().optional(),buyY:z.coerce.number().int().positive().nullable().optional(),productIds:z.array(z.string().uuid()).default([]),startDate:z.string().nullable().optional(),endDate:z.string().nullable().optional()}).parse(req.body);const c=await pool.connect();try{await c.query('begin');const offer=(await c.query('insert into offers(title_en,title_ar,type,value,bundle_price,buy_x,buy_y,start_date,end_date,active) values($1,$2,$3,$4,$5,$6,$7,$8,$9,true) returning *',[x.titleEn,x.titleAr,x.type,x.value,x.bundlePrice||null,x.buyX||null,x.buyY||null,x.startDate||null,x.endDate||null])).rows[0];for(const id of x.productIds)await c.query('insert into offer_items(offer_id,product_id) values($1,$2) on conflict do nothing',[offer.id,id]);await c.query('commit');res.status(201).json(offer)}catch(e){await c.query('rollback');throw e}finally{c.release()}}catch(e){res.status(400).json({error:e.message})}});

if(require.main===module){const port=process.env.PORT||4000;app.listen(port,()=>console.log('SAFA API listening on '+port))}
module.exports=app;
